version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: paper
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      MEMORY: 2G
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/ubuntu/data:/data
